application: vn-app
version: 1-0
runtime: python27
threadsafe: false
api_version: 1

builtins:
- remote_api: on
- appstats: on

includes:
- mapreduce/include.yaml

handlers:
- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin